### PR TITLE
Ignore tslint error about missing wheelDelta

### PR DESCRIPTION
**Pull request by dragly**

### CODE REVIEW

**Comment by dragly** [comment]
@nsunderland-cognite how come this showed up when I tried to build and not in your previous commit? (3cb4b688ada99b0ebd61cff595f5a9c384b8048f)

**Comment by nsunderland-cognite** [comment]
Because I screwed up. Sorry, I thought I fixed this.

**Comment by nsunderland-cognite** [comment]
This isn't a tslint error though, correct? It's a TypeScript error?

**Comment by dragly** [comment]
Yes, good point. I changed the commit message.

**Pull request merged**
